import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/lib/NavbarWrapper";
import Footer from "@/components/home-1/Footer";
import FooterWrapper from "@/lib/FooterWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Client wrapper handles visibility */}
        {/* <NavbarWrapper /> */}
        {children}
        {/* ✅ Dynamic Footer based on route */}
        {/* <FooterWrapper /> */}
      </body>
    </html>
  );
}
